# Generated by Django 3.2.5 on 2021-12-11 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandometer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='adress',
            new_name='address',
        ),
    ]
