# Generated by Django 3.2.5 on 2021-12-13 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandometer', '0002_rename_adress_club_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('band_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandometer.band')),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandometer.club')),
            ],
        ),
    ]
