# Generated by Django 3.2.5 on 2021-12-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandometer', '0003_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='band_id',
        ),
        migrations.AddField(
            model_name='event',
            name='band_id',
            field=models.ManyToManyField(to='bandometer.Band'),
        ),
    ]
